version: '3'

services:
  nginx:  
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports: 
      - 80:80 
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
  certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/
        - ./certbot/conf/:/etc/letsencrypt/
networks:
  default:
    external:
      name: ReplaceWithYourOwnNetwork